# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cloudrone_template_2.ui'
#
# Created: Mon Jul  4 17:15:45 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1280, 1024)
        self.horizontal = QtGui.QFrame(Form)
        self.horizontal.setGeometry(QtCore.QRect(0, 504, 1280, 5))
        self.horizontal.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal.setObjectName(_fromUtf8("horizontal"))
        self.vertical = QtGui.QFrame(Form)
        self.vertical.setGeometry(QtCore.QRect(640, 0, 5, 1024))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vertical.setFont(font)
        self.vertical.setFrameShape(QtGui.QFrame.VLine)
        self.vertical.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical.setObjectName(_fromUtf8("vertical"))
        self.Attitude_image_1 = QtGui.QLabel(Form)
        self.Attitude_image_1.setGeometry(QtCore.QRect(20, 20, 210, 210))
        self.Attitude_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_image_1.setObjectName(_fromUtf8("Attitude_image_1"))
        self.Attitude_name_1 = QtGui.QLabel(Form)
        self.Attitude_name_1.setGeometry(QtCore.QRect(20, 240, 210, 30))
        self.Attitude_name_1.setTextFormat(QtCore.Qt.RichText)
        self.Attitude_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_name_1.setObjectName(_fromUtf8("Attitude_name_1"))
        self.Turn_image_1 = QtGui.QLabel(Form)
        self.Turn_image_1.setGeometry(QtCore.QRect(20, 280, 210, 53))
        self.Turn_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_image_1.setObjectName(_fromUtf8("Turn_image_1"))
        self.Turn_name_1 = QtGui.QLabel(Form)
        self.Turn_name_1.setGeometry(QtCore.QRect(20, 343, 210, 30))
        self.Turn_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_name_1.setObjectName(_fromUtf8("Turn_name_1"))
        self.Altitude_name_1 = QtGui.QLabel(Form)
        self.Altitude_name_1.setGeometry(QtCore.QRect(20, 400, 70, 20))
        self.Altitude_name_1.setObjectName(_fromUtf8("Altitude_name_1"))
        self.Altitude_LCD_1 = QtGui.QLCDNumber(Form)
        self.Altitude_LCD_1.setGeometry(QtCore.QRect(130, 400, 64, 20))
        self.Altitude_LCD_1.setAutoFillBackground(True)
        self.Altitude_LCD_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.Altitude_LCD_1.setLineWidth(1)
        self.Altitude_LCD_1.setSmallDecimalPoint(False)
        self.Altitude_LCD_1.setDigitCount(5)
        self.Altitude_LCD_1.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.Altitude_LCD_1.setObjectName(_fromUtf8("Altitude_LCD_1"))
        self.Temperature_name_1 = QtGui.QLabel(Form)
        self.Temperature_name_1.setGeometry(QtCore.QRect(20, 430, 95, 20))
        self.Temperature_name_1.setObjectName(_fromUtf8("Temperature_name_1"))
        self.Temperature_LCD_1 = QtGui.QLCDNumber(Form)
        self.Temperature_LCD_1.setGeometry(QtCore.QRect(130, 430, 64, 20))
        self.Temperature_LCD_1.setAutoFillBackground(True)
        self.Temperature_LCD_1.setSmallDecimalPoint(False)
        self.Temperature_LCD_1.setProperty("intValue", 10)
        self.Temperature_LCD_1.setObjectName(_fromUtf8("Temperature_LCD_1"))
        self.Pressure_name_1 = QtGui.QLabel(Form)
        self.Pressure_name_1.setGeometry(QtCore.QRect(20, 460, 95, 20))
        self.Pressure_name_1.setObjectName(_fromUtf8("Pressure_name_1"))
        self.Pressure_LCD_1 = QtGui.QLCDNumber(Form)
        self.Pressure_LCD_1.setGeometry(QtCore.QRect(130, 460, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Pressure_LCD_1.setFont(font)
        self.Pressure_LCD_1.setAutoFillBackground(True)
        self.Pressure_LCD_1.setSmallDecimalPoint(False)
        self.Pressure_LCD_1.setNumDigits(5)
        self.Pressure_LCD_1.setDigitCount(5)
        self.Pressure_LCD_1.setProperty("value", 10.0)
        self.Pressure_LCD_1.setObjectName(_fromUtf8("Pressure_LCD_1"))
        self.Throttle_bar_1 = QtGui.QProgressBar(Form)
        self.Throttle_bar_1.setGeometry(QtCore.QRect(300, 280, 210, 53))
        self.Throttle_bar_1.setProperty("value", 24)
        self.Throttle_bar_1.setObjectName(_fromUtf8("Throttle_bar_1"))
        self.Throttle_name_1 = QtGui.QLabel(Form)
        self.Throttle_name_1.setGeometry(QtCore.QRect(300, 330, 210, 30))
        self.Throttle_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle_name_1.setObjectName(_fromUtf8("Throttle_name_1"))
        self.Battery_bar_1 = QtGui.QProgressBar(Form)
        self.Battery_bar_1.setGeometry(QtCore.QRect(340, 20, 53, 210))
        self.Battery_bar_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Battery_bar_1.setProperty("value", 24)
        self.Battery_bar_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery_bar_1.setTextVisible(True)
        self.Battery_bar_1.setOrientation(QtCore.Qt.Vertical)
        self.Battery_bar_1.setInvertedAppearance(False)
        self.Battery_bar_1.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.Battery_bar_1.setObjectName(_fromUtf8("Battery_bar_1"))
        self.Battery_name_1 = QtGui.QLabel(Form)
        self.Battery_name_1.setGeometry(QtCore.QRect(260, 230, 210, 30))
        self.Battery_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Battery_name_1.setObjectName(_fromUtf8("Battery_name_1"))
        self.button_1 = QtGui.QPushButton(Form)
        self.button_1.setGeometry(QtCore.QRect(593, 489, 100, 30))
        self.button_1.setObjectName(_fromUtf8("button_1"))
        self.quad_name_1 = QtGui.QLabel(Form)
        self.quad_name_1.setGeometry(QtCore.QRect(290, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.quad_name_1.setFont(font)
        self.quad_name_1.setObjectName(_fromUtf8("quad_name_1"))
        self.Altitude_unit_1 = QtGui.QLabel(Form)
        self.Altitude_unit_1.setGeometry(QtCore.QRect(200, 400, 31, 17))
        self.Altitude_unit_1.setObjectName(_fromUtf8("Altitude_unit_1"))
        self.Temperature_unit_1 = QtGui.QLabel(Form)
        self.Temperature_unit_1.setGeometry(QtCore.QRect(200, 430, 21, 17))
        self.Temperature_unit_1.setObjectName(_fromUtf8("Temperature_unit_1"))
        self.Pressure_unit_1 = QtGui.QLabel(Form)
        self.Pressure_unit_1.setGeometry(QtCore.QRect(200, 460, 31, 17))
        self.Pressure_unit_1.setObjectName(_fromUtf8("Pressure_unit_1"))
        self.Voltage_name_1 = QtGui.QLabel(Form)
        self.Voltage_name_1.setGeometry(QtCore.QRect(430, 60, 70, 20))
        self.Voltage_name_1.setObjectName(_fromUtf8("Voltage_name_1"))
        self.Voltage_LCD_1 = QtGui.QLCDNumber(Form)
        self.Voltage_LCD_1.setGeometry(QtCore.QRect(500, 60, 70, 20))
        self.Voltage_LCD_1.setObjectName(_fromUtf8("Voltage_LCD_1"))
        self.Voltage_unit_1 = QtGui.QLabel(Form)
        self.Voltage_unit_1.setGeometry(QtCore.QRect(580, 60, 20, 20))
        self.Voltage_unit_1.setObjectName(_fromUtf8("Voltage_unit_1"))
        self.Attitude_image_2 = QtGui.QLabel(Form)
        self.Attitude_image_2.setGeometry(QtCore.QRect(20, 524, 210, 210))
        self.Attitude_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_image_2.setObjectName(_fromUtf8("Attitude_image_2"))
        self.Attitude_name_2 = QtGui.QLabel(Form)
        self.Attitude_name_2.setGeometry(QtCore.QRect(20, 744, 210, 30))
        self.Attitude_name_2.setTextFormat(QtCore.Qt.RichText)
        self.Attitude_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_name_2.setObjectName(_fromUtf8("Attitude_name_2"))
        self.Turn_image_2 = QtGui.QLabel(Form)
        self.Turn_image_2.setGeometry(QtCore.QRect(20, 784, 210, 53))
        self.Turn_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_image_2.setObjectName(_fromUtf8("Turn_image_2"))
        self.Turn_name_2 = QtGui.QLabel(Form)
        self.Turn_name_2.setGeometry(QtCore.QRect(20, 847, 210, 30))
        self.Turn_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_name_2.setObjectName(_fromUtf8("Turn_name_2"))
        self.Altitude_LCD_2 = QtGui.QLCDNumber(Form)
        self.Altitude_LCD_2.setGeometry(QtCore.QRect(130, 904, 64, 20))
        self.Altitude_LCD_2.setAutoFillBackground(True)
        self.Altitude_LCD_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.Altitude_LCD_2.setLineWidth(1)
        self.Altitude_LCD_2.setSmallDecimalPoint(False)
        self.Altitude_LCD_2.setDigitCount(5)
        self.Altitude_LCD_2.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.Altitude_LCD_2.setObjectName(_fromUtf8("Altitude_LCD_2"))
        self.Temperature_unit_2 = QtGui.QLabel(Form)
        self.Temperature_unit_2.setGeometry(QtCore.QRect(200, 934, 21, 17))
        self.Temperature_unit_2.setObjectName(_fromUtf8("Temperature_unit_2"))
        self.Temperature_name_2 = QtGui.QLabel(Form)
        self.Temperature_name_2.setGeometry(QtCore.QRect(20, 934, 95, 20))
        self.Temperature_name_2.setObjectName(_fromUtf8("Temperature_name_2"))
        self.Pressure_LCD_2 = QtGui.QLCDNumber(Form)
        self.Pressure_LCD_2.setGeometry(QtCore.QRect(130, 964, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Pressure_LCD_2.setFont(font)
        self.Pressure_LCD_2.setAutoFillBackground(True)
        self.Pressure_LCD_2.setSmallDecimalPoint(False)
        self.Pressure_LCD_2.setNumDigits(5)
        self.Pressure_LCD_2.setDigitCount(5)
        self.Pressure_LCD_2.setProperty("value", 10.0)
        self.Pressure_LCD_2.setObjectName(_fromUtf8("Pressure_LCD_2"))
        self.Pressure_name_2 = QtGui.QLabel(Form)
        self.Pressure_name_2.setGeometry(QtCore.QRect(20, 964, 95, 20))
        self.Pressure_name_2.setObjectName(_fromUtf8("Pressure_name_2"))
        self.Pressure_unit_2 = QtGui.QLabel(Form)
        self.Pressure_unit_2.setGeometry(QtCore.QRect(200, 964, 31, 17))
        self.Pressure_unit_2.setObjectName(_fromUtf8("Pressure_unit_2"))
        self.Altitude_unit_2 = QtGui.QLabel(Form)
        self.Altitude_unit_2.setGeometry(QtCore.QRect(200, 904, 31, 17))
        self.Altitude_unit_2.setObjectName(_fromUtf8("Altitude_unit_2"))
        self.Altitude_name_2 = QtGui.QLabel(Form)
        self.Altitude_name_2.setGeometry(QtCore.QRect(20, 904, 70, 20))
        self.Altitude_name_2.setObjectName(_fromUtf8("Altitude_name_2"))
        self.Temperature_LCD_2 = QtGui.QLCDNumber(Form)
        self.Temperature_LCD_2.setGeometry(QtCore.QRect(130, 934, 64, 20))
        self.Temperature_LCD_2.setAutoFillBackground(True)
        self.Temperature_LCD_2.setSmallDecimalPoint(False)
        self.Temperature_LCD_2.setProperty("intValue", 10)
        self.Temperature_LCD_2.setObjectName(_fromUtf8("Temperature_LCD_2"))
        self.Battery_name_2 = QtGui.QLabel(Form)
        self.Battery_name_2.setGeometry(QtCore.QRect(260, 734, 210, 30))
        self.Battery_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Battery_name_2.setObjectName(_fromUtf8("Battery_name_2"))
        self.Voltage_LCD_2 = QtGui.QLCDNumber(Form)
        self.Voltage_LCD_2.setGeometry(QtCore.QRect(500, 564, 70, 20))
        self.Voltage_LCD_2.setObjectName(_fromUtf8("Voltage_LCD_2"))
        self.Voltage_name_2 = QtGui.QLabel(Form)
        self.Voltage_name_2.setGeometry(QtCore.QRect(430, 564, 70, 20))
        self.Voltage_name_2.setObjectName(_fromUtf8("Voltage_name_2"))
        self.Battery_bar_2 = QtGui.QProgressBar(Form)
        self.Battery_bar_2.setGeometry(QtCore.QRect(340, 524, 53, 210))
        self.Battery_bar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Battery_bar_2.setProperty("value", 24)
        self.Battery_bar_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery_bar_2.setTextVisible(True)
        self.Battery_bar_2.setOrientation(QtCore.Qt.Vertical)
        self.Battery_bar_2.setInvertedAppearance(False)
        self.Battery_bar_2.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.Battery_bar_2.setObjectName(_fromUtf8("Battery_bar_2"))
        self.Voltage_unit_2 = QtGui.QLabel(Form)
        self.Voltage_unit_2.setGeometry(QtCore.QRect(580, 564, 20, 20))
        self.Voltage_unit_2.setObjectName(_fromUtf8("Voltage_unit_2"))
        self.Throttle_bar_2 = QtGui.QProgressBar(Form)
        self.Throttle_bar_2.setGeometry(QtCore.QRect(300, 784, 210, 53))
        self.Throttle_bar_2.setProperty("value", 24)
        self.Throttle_bar_2.setObjectName(_fromUtf8("Throttle_bar_2"))
        self.quad_name_2 = QtGui.QLabel(Form)
        self.quad_name_2.setGeometry(QtCore.QRect(290, 924, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.quad_name_2.setFont(font)
        self.quad_name_2.setObjectName(_fromUtf8("quad_name_2"))
        self.Throttle_name_2 = QtGui.QLabel(Form)
        self.Throttle_name_2.setGeometry(QtCore.QRect(300, 834, 210, 30))
        self.Throttle_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle_name_2.setObjectName(_fromUtf8("Throttle_name_2"))
        self.Turn_image_3 = QtGui.QLabel(Form)
        self.Turn_image_3.setGeometry(QtCore.QRect(660, 280, 210, 53))
        self.Turn_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_image_3.setObjectName(_fromUtf8("Turn_image_3"))
        self.Turn_name_3 = QtGui.QLabel(Form)
        self.Turn_name_3.setGeometry(QtCore.QRect(660, 343, 210, 30))
        self.Turn_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_name_3.setObjectName(_fromUtf8("Turn_name_3"))
        self.Attitude_image_3 = QtGui.QLabel(Form)
        self.Attitude_image_3.setGeometry(QtCore.QRect(660, 20, 210, 210))
        self.Attitude_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_image_3.setObjectName(_fromUtf8("Attitude_image_3"))
        self.Attitude_name_3 = QtGui.QLabel(Form)
        self.Attitude_name_3.setGeometry(QtCore.QRect(660, 240, 210, 30))
        self.Attitude_name_3.setTextFormat(QtCore.Qt.RichText)
        self.Attitude_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_name_3.setObjectName(_fromUtf8("Attitude_name_3"))
        self.Altitude_LCD_3 = QtGui.QLCDNumber(Form)
        self.Altitude_LCD_3.setGeometry(QtCore.QRect(770, 400, 64, 20))
        self.Altitude_LCD_3.setAutoFillBackground(True)
        self.Altitude_LCD_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.Altitude_LCD_3.setLineWidth(1)
        self.Altitude_LCD_3.setSmallDecimalPoint(False)
        self.Altitude_LCD_3.setDigitCount(5)
        self.Altitude_LCD_3.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.Altitude_LCD_3.setObjectName(_fromUtf8("Altitude_LCD_3"))
        self.Temperature_unit_3 = QtGui.QLabel(Form)
        self.Temperature_unit_3.setGeometry(QtCore.QRect(840, 430, 21, 17))
        self.Temperature_unit_3.setObjectName(_fromUtf8("Temperature_unit_3"))
        self.Temperature_name_3 = QtGui.QLabel(Form)
        self.Temperature_name_3.setGeometry(QtCore.QRect(660, 430, 95, 20))
        self.Temperature_name_3.setObjectName(_fromUtf8("Temperature_name_3"))
        self.Pressure_LCD_3 = QtGui.QLCDNumber(Form)
        self.Pressure_LCD_3.setGeometry(QtCore.QRect(770, 460, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Pressure_LCD_3.setFont(font)
        self.Pressure_LCD_3.setAutoFillBackground(True)
        self.Pressure_LCD_3.setSmallDecimalPoint(False)
        self.Pressure_LCD_3.setNumDigits(5)
        self.Pressure_LCD_3.setDigitCount(5)
        self.Pressure_LCD_3.setProperty("value", 10.0)
        self.Pressure_LCD_3.setObjectName(_fromUtf8("Pressure_LCD_3"))
        self.Pressure_name_3 = QtGui.QLabel(Form)
        self.Pressure_name_3.setGeometry(QtCore.QRect(660, 460, 95, 20))
        self.Pressure_name_3.setObjectName(_fromUtf8("Pressure_name_3"))
        self.Pressure_unit_3 = QtGui.QLabel(Form)
        self.Pressure_unit_3.setGeometry(QtCore.QRect(840, 460, 31, 17))
        self.Pressure_unit_3.setObjectName(_fromUtf8("Pressure_unit_3"))
        self.Altitude_unit_3 = QtGui.QLabel(Form)
        self.Altitude_unit_3.setGeometry(QtCore.QRect(840, 400, 31, 17))
        self.Altitude_unit_3.setObjectName(_fromUtf8("Altitude_unit_3"))
        self.Altitude_name_3 = QtGui.QLabel(Form)
        self.Altitude_name_3.setGeometry(QtCore.QRect(660, 400, 70, 20))
        self.Altitude_name_3.setObjectName(_fromUtf8("Altitude_name_3"))
        self.Temperature_LCD_3 = QtGui.QLCDNumber(Form)
        self.Temperature_LCD_3.setGeometry(QtCore.QRect(770, 430, 64, 20))
        self.Temperature_LCD_3.setAutoFillBackground(True)
        self.Temperature_LCD_3.setSmallDecimalPoint(False)
        self.Temperature_LCD_3.setProperty("intValue", 10)
        self.Temperature_LCD_3.setObjectName(_fromUtf8("Temperature_LCD_3"))
        self.Battery_name_3 = QtGui.QLabel(Form)
        self.Battery_name_3.setGeometry(QtCore.QRect(870, 230, 210, 30))
        self.Battery_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Battery_name_3.setObjectName(_fromUtf8("Battery_name_3"))
        self.Voltage_LCD_3 = QtGui.QLCDNumber(Form)
        self.Voltage_LCD_3.setGeometry(QtCore.QRect(1110, 60, 70, 20))
        self.Voltage_LCD_3.setObjectName(_fromUtf8("Voltage_LCD_3"))
        self.Voltage_name_3 = QtGui.QLabel(Form)
        self.Voltage_name_3.setGeometry(QtCore.QRect(1040, 60, 70, 20))
        self.Voltage_name_3.setObjectName(_fromUtf8("Voltage_name_3"))
        self.Battery_bar_3 = QtGui.QProgressBar(Form)
        self.Battery_bar_3.setGeometry(QtCore.QRect(950, 20, 53, 210))
        self.Battery_bar_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Battery_bar_3.setProperty("value", 24)
        self.Battery_bar_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery_bar_3.setTextVisible(True)
        self.Battery_bar_3.setOrientation(QtCore.Qt.Vertical)
        self.Battery_bar_3.setInvertedAppearance(False)
        self.Battery_bar_3.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.Battery_bar_3.setObjectName(_fromUtf8("Battery_bar_3"))
        self.Voltage_unit_3 = QtGui.QLabel(Form)
        self.Voltage_unit_3.setGeometry(QtCore.QRect(1190, 60, 20, 20))
        self.Voltage_unit_3.setObjectName(_fromUtf8("Voltage_unit_3"))
        self.Throttle_bar_3 = QtGui.QProgressBar(Form)
        self.Throttle_bar_3.setGeometry(QtCore.QRect(910, 280, 210, 53))
        self.Throttle_bar_3.setProperty("value", 24)
        self.Throttle_bar_3.setObjectName(_fromUtf8("Throttle_bar_3"))
        self.quad_name_3 = QtGui.QLabel(Form)
        self.quad_name_3.setGeometry(QtCore.QRect(910, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.quad_name_3.setFont(font)
        self.quad_name_3.setObjectName(_fromUtf8("quad_name_3"))
        self.Throttle_name_3 = QtGui.QLabel(Form)
        self.Throttle_name_3.setGeometry(QtCore.QRect(910, 330, 210, 30))
        self.Throttle_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle_name_3.setObjectName(_fromUtf8("Throttle_name_3"))
        self.Attitude_image_4 = QtGui.QLabel(Form)
        self.Attitude_image_4.setGeometry(QtCore.QRect(660, 524, 210, 210))
        self.Attitude_image_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_image_4.setObjectName(_fromUtf8("Attitude_image_4"))
        self.Turn_image_4 = QtGui.QLabel(Form)
        self.Turn_image_4.setGeometry(QtCore.QRect(660, 784, 210, 53))
        self.Turn_image_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_image_4.setObjectName(_fromUtf8("Turn_image_4"))
        self.Turn_name_4 = QtGui.QLabel(Form)
        self.Turn_name_4.setGeometry(QtCore.QRect(660, 847, 210, 30))
        self.Turn_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_name_4.setObjectName(_fromUtf8("Turn_name_4"))
        self.Attitude_name_4 = QtGui.QLabel(Form)
        self.Attitude_name_4.setGeometry(QtCore.QRect(660, 744, 210, 30))
        self.Attitude_name_4.setTextFormat(QtCore.Qt.RichText)
        self.Attitude_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_name_4.setObjectName(_fromUtf8("Attitude_name_4"))
        self.Temperature_name_4 = QtGui.QLabel(Form)
        self.Temperature_name_4.setGeometry(QtCore.QRect(660, 934, 95, 20))
        self.Temperature_name_4.setObjectName(_fromUtf8("Temperature_name_4"))
        self.Temperature_LCD_4 = QtGui.QLCDNumber(Form)
        self.Temperature_LCD_4.setGeometry(QtCore.QRect(770, 934, 64, 20))
        self.Temperature_LCD_4.setAutoFillBackground(True)
        self.Temperature_LCD_4.setSmallDecimalPoint(False)
        self.Temperature_LCD_4.setProperty("intValue", 10)
        self.Temperature_LCD_4.setObjectName(_fromUtf8("Temperature_LCD_4"))
        self.Altitude_LCD_4 = QtGui.QLCDNumber(Form)
        self.Altitude_LCD_4.setGeometry(QtCore.QRect(770, 904, 64, 20))
        self.Altitude_LCD_4.setAutoFillBackground(True)
        self.Altitude_LCD_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.Altitude_LCD_4.setLineWidth(1)
        self.Altitude_LCD_4.setSmallDecimalPoint(False)
        self.Altitude_LCD_4.setDigitCount(5)
        self.Altitude_LCD_4.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.Altitude_LCD_4.setObjectName(_fromUtf8("Altitude_LCD_4"))
        self.Altitude_unit_4 = QtGui.QLabel(Form)
        self.Altitude_unit_4.setGeometry(QtCore.QRect(840, 904, 31, 17))
        self.Altitude_unit_4.setObjectName(_fromUtf8("Altitude_unit_4"))
        self.Temperature_unit_4 = QtGui.QLabel(Form)
        self.Temperature_unit_4.setGeometry(QtCore.QRect(840, 934, 21, 17))
        self.Temperature_unit_4.setObjectName(_fromUtf8("Temperature_unit_4"))
        self.Pressure_unit_4 = QtGui.QLabel(Form)
        self.Pressure_unit_4.setGeometry(QtCore.QRect(840, 964, 31, 17))
        self.Pressure_unit_4.setObjectName(_fromUtf8("Pressure_unit_4"))
        self.Pressure_LCD_4 = QtGui.QLCDNumber(Form)
        self.Pressure_LCD_4.setGeometry(QtCore.QRect(770, 964, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Pressure_LCD_4.setFont(font)
        self.Pressure_LCD_4.setAutoFillBackground(True)
        self.Pressure_LCD_4.setSmallDecimalPoint(False)
        self.Pressure_LCD_4.setNumDigits(5)
        self.Pressure_LCD_4.setDigitCount(5)
        self.Pressure_LCD_4.setProperty("value", 10.0)
        self.Pressure_LCD_4.setObjectName(_fromUtf8("Pressure_LCD_4"))
        self.Pressure_name_4 = QtGui.QLabel(Form)
        self.Pressure_name_4.setGeometry(QtCore.QRect(660, 964, 95, 20))
        self.Pressure_name_4.setObjectName(_fromUtf8("Pressure_name_4"))
        self.Altitude_name_4 = QtGui.QLabel(Form)
        self.Altitude_name_4.setGeometry(QtCore.QRect(660, 904, 70, 20))
        self.Altitude_name_4.setObjectName(_fromUtf8("Altitude_name_4"))
        self.Battery_bar_4 = QtGui.QProgressBar(Form)
        self.Battery_bar_4.setGeometry(QtCore.QRect(950, 524, 53, 210))
        self.Battery_bar_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Battery_bar_4.setProperty("value", 24)
        self.Battery_bar_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery_bar_4.setTextVisible(True)
        self.Battery_bar_4.setOrientation(QtCore.Qt.Vertical)
        self.Battery_bar_4.setInvertedAppearance(False)
        self.Battery_bar_4.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.Battery_bar_4.setObjectName(_fromUtf8("Battery_bar_4"))
        self.Battery_name_4 = QtGui.QLabel(Form)
        self.Battery_name_4.setGeometry(QtCore.QRect(870, 734, 210, 30))
        self.Battery_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Battery_name_4.setObjectName(_fromUtf8("Battery_name_4"))
        self.Throttle_name_4 = QtGui.QLabel(Form)
        self.Throttle_name_4.setGeometry(QtCore.QRect(910, 834, 210, 30))
        self.Throttle_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle_name_4.setObjectName(_fromUtf8("Throttle_name_4"))
        self.Throttle_bar_4 = QtGui.QProgressBar(Form)
        self.Throttle_bar_4.setGeometry(QtCore.QRect(910, 784, 210, 53))
        self.Throttle_bar_4.setProperty("value", 24)
        self.Throttle_bar_4.setObjectName(_fromUtf8("Throttle_bar_4"))
        self.Voltage_LCD_4 = QtGui.QLCDNumber(Form)
        self.Voltage_LCD_4.setGeometry(QtCore.QRect(1110, 564, 70, 20))
        self.Voltage_LCD_4.setObjectName(_fromUtf8("Voltage_LCD_4"))
        self.Voltage_unit_4 = QtGui.QLabel(Form)
        self.Voltage_unit_4.setGeometry(QtCore.QRect(1190, 564, 20, 20))
        self.Voltage_unit_4.setObjectName(_fromUtf8("Voltage_unit_4"))
        self.Voltage_name_4 = QtGui.QLabel(Form)
        self.Voltage_name_4.setGeometry(QtCore.QRect(1040, 564, 70, 20))
        self.Voltage_name_4.setObjectName(_fromUtf8("Voltage_name_4"))
        self.quad_name_4 = QtGui.QLabel(Form)
        self.quad_name_4.setGeometry(QtCore.QRect(910, 924, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.quad_name_4.setFont(font)
        self.quad_name_4.setObjectName(_fromUtf8("quad_name_4"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.Attitude_image_1.setText(_translate("Form", "attitude_image", None))
        self.Attitude_name_1.setText(_translate("Form", "Attitude Indicator", None))
        self.Turn_image_1.setText(_translate("Form", "Turn_image", None))
        self.Turn_name_1.setText(_translate("Form", "Turn Indicator", None))
        self.Altitude_name_1.setText(_translate("Form", "Altitude : ", None))
        self.Temperature_name_1.setText(_translate("Form", "Temperature : ", None))
        self.Pressure_name_1.setText(_translate("Form", "Pressure :", None))
        self.Throttle_name_1.setText(_translate("Form", "Throttle Level", None))
        self.Battery_bar_1.setFormat(_translate("Form", "%p%", None))
        self.Battery_name_1.setText(_translate("Form", "Battery Level", None))
        self.button_1.setText(_translate("Form", "EXIT", None))
        self.quad_name_1.setText(_translate("Form", "CLOUDRONE 1", None))
        self.Altitude_unit_1.setText(_translate("Form", "mts", None))
        self.Temperature_unit_1.setText(_translate("Form", "C", None))
        self.Pressure_unit_1.setText(_translate("Form", "bar", None))
        self.Voltage_name_1.setText(_translate("Form", "Voltage :", None))
        self.Voltage_unit_1.setText(_translate("Form", "V", None))
        self.Attitude_image_2.setText(_translate("Form", "attitude_image", None))
        self.Attitude_name_2.setText(_translate("Form", "Attitude Indicator", None))
        self.Turn_image_2.setText(_translate("Form", "Turn_image", None))
        self.Turn_name_2.setText(_translate("Form", "Turn Indicator", None))
        self.Temperature_unit_2.setText(_translate("Form", "C", None))
        self.Temperature_name_2.setText(_translate("Form", "Temperature : ", None))
        self.Pressure_name_2.setText(_translate("Form", "Pressure :", None))
        self.Pressure_unit_2.setText(_translate("Form", "bar", None))
        self.Altitude_unit_2.setText(_translate("Form", "mts", None))
        self.Altitude_name_2.setText(_translate("Form", "Altitude : ", None))
        self.Battery_name_2.setText(_translate("Form", "Battery Level", None))
        self.Voltage_name_2.setText(_translate("Form", "Voltage :", None))
        self.Battery_bar_2.setFormat(_translate("Form", "%p%", None))
        self.Voltage_unit_2.setText(_translate("Form", "V", None))
        self.quad_name_2.setText(_translate("Form", "CLOUDRONE 2", None))
        self.Throttle_name_2.setText(_translate("Form", "Throttle Level", None))
        self.Turn_image_3.setText(_translate("Form", "Turn_image", None))
        self.Turn_name_3.setText(_translate("Form", "Turn Indicator", None))
        self.Attitude_image_3.setText(_translate("Form", "attitude_image", None))
        self.Attitude_name_3.setText(_translate("Form", "Attitude Indicator", None))
        self.Temperature_unit_3.setText(_translate("Form", "C", None))
        self.Temperature_name_3.setText(_translate("Form", "Temperature : ", None))
        self.Pressure_name_3.setText(_translate("Form", "Pressure :", None))
        self.Pressure_unit_3.setText(_translate("Form", "bar", None))
        self.Altitude_unit_3.setText(_translate("Form", "mts", None))
        self.Altitude_name_3.setText(_translate("Form", "Altitude : ", None))
        self.Battery_name_3.setText(_translate("Form", "Battery Level", None))
        self.Voltage_name_3.setText(_translate("Form", "Voltage :", None))
        self.Battery_bar_3.setFormat(_translate("Form", "%p%", None))
        self.Voltage_unit_3.setText(_translate("Form", "V", None))
        self.quad_name_3.setText(_translate("Form", "CLOUDRONE 3", None))
        self.Throttle_name_3.setText(_translate("Form", "Throttle Level", None))
        self.Attitude_image_4.setText(_translate("Form", "attitude_image", None))
        self.Turn_image_4.setText(_translate("Form", "Turn_image", None))
        self.Turn_name_4.setText(_translate("Form", "Turn Indicator", None))
        self.Attitude_name_4.setText(_translate("Form", "Attitude Indicator", None))
        self.Temperature_name_4.setText(_translate("Form", "Temperature : ", None))
        self.Altitude_unit_4.setText(_translate("Form", "mts", None))
        self.Temperature_unit_4.setText(_translate("Form", "C", None))
        self.Pressure_unit_4.setText(_translate("Form", "bar", None))
        self.Pressure_name_4.setText(_translate("Form", "Pressure :", None))
        self.Altitude_name_4.setText(_translate("Form", "Altitude : ", None))
        self.Battery_bar_4.setFormat(_translate("Form", "%p%", None))
        self.Battery_name_4.setText(_translate("Form", "Battery Level", None))
        self.Throttle_name_4.setText(_translate("Form", "Throttle Level", None))
        self.Voltage_unit_4.setText(_translate("Form", "V", None))
        self.Voltage_name_4.setText(_translate("Form", "Voltage :", None))
        self.quad_name_4.setText(_translate("Form", "CLOUDRONE 4", None))

