# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cloudrone_template_1.ui'
#
# Created: Sat Jul  2 15:07:38 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1280, 1024)
        self.horizontal = QtGui.QFrame(Form)
        self.horizontal.setGeometry(QtCore.QRect(0, 504, 1280, 5))
        self.horizontal.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal.setObjectName(_fromUtf8("horizontal"))
        self.vertical = QtGui.QFrame(Form)
        self.vertical.setGeometry(QtCore.QRect(640, 0, 5, 1024))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vertical.setFont(font)
        self.vertical.setFrameShape(QtGui.QFrame.VLine)
        self.vertical.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical.setObjectName(_fromUtf8("vertical"))
        self.Attitude_image_1 = QtGui.QLabel(Form)
        self.Attitude_image_1.setGeometry(QtCore.QRect(20, 20, 210, 210))
        self.Attitude_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_image_1.setObjectName(_fromUtf8("Attitude_image_1"))
        self.Attitude_name_1 = QtGui.QLabel(Form)
        self.Attitude_name_1.setGeometry(QtCore.QRect(20, 240, 210, 30))
        self.Attitude_name_1.setTextFormat(QtCore.Qt.RichText)
        self.Attitude_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Attitude_name_1.setObjectName(_fromUtf8("Attitude_name_1"))
        self.Turn_image_1 = QtGui.QLabel(Form)
        self.Turn_image_1.setGeometry(QtCore.QRect(20, 280, 210, 53))
        self.Turn_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_image_1.setObjectName(_fromUtf8("Turn_image_1"))
        self.Turn_name_1 = QtGui.QLabel(Form)
        self.Turn_name_1.setGeometry(QtCore.QRect(20, 343, 210, 30))
        self.Turn_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Turn_name_1.setObjectName(_fromUtf8("Turn_name_1"))
        self.Altitude_name_1 = QtGui.QLabel(Form)
        self.Altitude_name_1.setGeometry(QtCore.QRect(20, 400, 70, 20))
        self.Altitude_name_1.setObjectName(_fromUtf8("Altitude_name_1"))
        self.Altitude_LCD_1 = QtGui.QLCDNumber(Form)
        self.Altitude_LCD_1.setGeometry(QtCore.QRect(130, 400, 64, 20))
        self.Altitude_LCD_1.setAutoFillBackground(True)
        self.Altitude_LCD_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.Altitude_LCD_1.setLineWidth(1)
        self.Altitude_LCD_1.setSmallDecimalPoint(False)
        self.Altitude_LCD_1.setDigitCount(5)
        self.Altitude_LCD_1.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.Altitude_LCD_1.setObjectName(_fromUtf8("Altitude_LCD_1"))
        self.Temperature_name_1 = QtGui.QLabel(Form)
        self.Temperature_name_1.setGeometry(QtCore.QRect(20, 430, 95, 20))
        self.Temperature_name_1.setObjectName(_fromUtf8("Temperature_name_1"))
        self.Temperature_LCD_1 = QtGui.QLCDNumber(Form)
        self.Temperature_LCD_1.setGeometry(QtCore.QRect(130, 430, 64, 20))
        self.Temperature_LCD_1.setAutoFillBackground(True)
        self.Temperature_LCD_1.setSmallDecimalPoint(False)
        self.Temperature_LCD_1.setProperty("intValue", 10)
        self.Temperature_LCD_1.setObjectName(_fromUtf8("Temperature_LCD_1"))
        self.Pressure_name_1 = QtGui.QLabel(Form)
        self.Pressure_name_1.setGeometry(QtCore.QRect(20, 460, 95, 20))
        self.Pressure_name_1.setObjectName(_fromUtf8("Pressure_name_1"))
        self.Pressure_LCD_1 = QtGui.QLCDNumber(Form)
        self.Pressure_LCD_1.setGeometry(QtCore.QRect(130, 460, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.Pressure_LCD_1.setFont(font)
        self.Pressure_LCD_1.setAutoFillBackground(True)
        self.Pressure_LCD_1.setSmallDecimalPoint(False)
        self.Pressure_LCD_1.setNumDigits(5)
        self.Pressure_LCD_1.setDigitCount(5)
        self.Pressure_LCD_1.setProperty("value", 10.0)
        self.Pressure_LCD_1.setObjectName(_fromUtf8("Pressure_LCD_1"))
        self.Throttle_bar_1 = QtGui.QProgressBar(Form)
        self.Throttle_bar_1.setGeometry(QtCore.QRect(300, 280, 210, 53))
        self.Throttle_bar_1.setProperty("value", 24)
        self.Throttle_bar_1.setObjectName(_fromUtf8("Throttle_bar_1"))
        self.Throttle_name_1 = QtGui.QLabel(Form)
        self.Throttle_name_1.setGeometry(QtCore.QRect(300, 330, 210, 30))
        self.Throttle_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Throttle_name_1.setObjectName(_fromUtf8("Throttle_name_1"))
        self.Battery_bar_1 = QtGui.QProgressBar(Form)
        self.Battery_bar_1.setGeometry(QtCore.QRect(340, 20, 53, 210))
        self.Battery_bar_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Battery_bar_1.setProperty("value", 24)
        self.Battery_bar_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery_bar_1.setTextVisible(True)
        self.Battery_bar_1.setOrientation(QtCore.Qt.Vertical)
        self.Battery_bar_1.setInvertedAppearance(False)
        self.Battery_bar_1.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.Battery_bar_1.setObjectName(_fromUtf8("Battery_bar_1"))
        self.Battery_name_1 = QtGui.QLabel(Form)
        self.Battery_name_1.setGeometry(QtCore.QRect(260, 230, 210, 30))
        self.Battery_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Battery_name_1.setObjectName(_fromUtf8("Battery_name_1"))
        self.button_1 = QtGui.QPushButton(Form)
        self.button_1.setGeometry(QtCore.QRect(590, 489, 100, 30))
        self.button_1.setObjectName(_fromUtf8("button_1"))
        self.quad_name_1 = QtGui.QLabel(Form)
        self.quad_name_1.setGeometry(QtCore.QRect(290, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.quad_name_1.setFont(font)
        self.quad_name_1.setObjectName(_fromUtf8("quad_name_1"))
        self.Altitude_unit_1 = QtGui.QLabel(Form)
        self.Altitude_unit_1.setGeometry(QtCore.QRect(200, 400, 31, 17))
        self.Altitude_unit_1.setObjectName(_fromUtf8("Altitude_unit_1"))
        self.Temperature_unit_1 = QtGui.QLabel(Form)
        self.Temperature_unit_1.setGeometry(QtCore.QRect(200, 430, 21, 17))
        self.Temperature_unit_1.setObjectName(_fromUtf8("Temperature_unit_1"))
        self.Pressure_unit_1 = QtGui.QLabel(Form)
        self.Pressure_unit_1.setGeometry(QtCore.QRect(200, 460, 31, 17))
        self.Pressure_unit_1.setObjectName(_fromUtf8("Pressure_unit_1"))
        self.Voltage_name_1 = QtGui.QLabel(Form)
        self.Voltage_name_1.setGeometry(QtCore.QRect(430, 60, 70, 20))
        self.Voltage_name_1.setObjectName(_fromUtf8("Voltage_name_1"))
        self.Voltage_LCD_1 = QtGui.QLCDNumber(Form)
        self.Voltage_LCD_1.setGeometry(QtCore.QRect(500, 60, 70, 20))
        self.Voltage_LCD_1.setObjectName(_fromUtf8("Voltage_LCD_1"))
        self.Voltage_unit_1 = QtGui.QLabel(Form)
        self.Voltage_unit_1.setGeometry(QtCore.QRect(580, 60, 20, 20))
        self.Voltage_unit_1.setObjectName(_fromUtf8("Voltage_unit_1"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.Attitude_image_1.setText(_translate("Form", "attitude_image", None))
        self.Attitude_name_1.setText(_translate("Form", "Attitude Indicator", None))
        self.Turn_image_1.setText(_translate("Form", "Turn_image", None))
        self.Turn_name_1.setText(_translate("Form", "Turn Indicator", None))
        self.Altitude_name_1.setText(_translate("Form", "Altitude : ", None))
        self.Temperature_name_1.setText(_translate("Form", "Temperature : ", None))
        self.Pressure_name_1.setText(_translate("Form", "Pressure :", None))
        self.Throttle_name_1.setText(_translate("Form", "Throttle Level", None))
        self.Battery_bar_1.setFormat(_translate("Form", "%p%", None))
        self.Battery_name_1.setText(_translate("Form", "Battery Level", None))
        self.button_1.setText(_translate("Form", "EXIT", None))
        self.quad_name_1.setText(_translate("Form", "CLOUDRONE 1", None))
        self.Altitude_unit_1.setText(_translate("Form", "mts", None))
        self.Temperature_unit_1.setText(_translate("Form", "C", None))
        self.Pressure_unit_1.setText(_translate("Form", "bar", None))
        self.Voltage_name_1.setText(_translate("Form", "Voltage :", None))
        self.Voltage_unit_1.setText(_translate("Form", "V", None))

